[package]
name = "yew-rs-tailwind-template"
version = "0.1.0"
edition = "2021"
description = "Yew.rs template for tailwindcss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = "0.19"
yew-router = "0.16.0"
