# An example Trunk.toml with all possible fields along with their defaults.

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 3000
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false

[[hooks]]
stage = "pre_build"
command ="cargo"
command_arguments = ["fmt"]

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = ["-c", "./tailwind.config.js", "-o", "./public/css/out.css", "--minify"]
